# CI workflow to release and renew the public ip of an Oracle Cloud compute server.

name: Oracle Cloud Infrastructure CI

# Controls when the workflow will run
on:
  # Schedule workflow for 12:00 UTC Sunday and Thursday
  schedule:
    - cron: '0 12 * * 0,4'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      OCI_SECRETS: ${{ secrets.OCISECRETS }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.17
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Install Lua
        run: sudo apt-get install lua5.4

      - name: Prep CI environment
        run: lua oci-prep-setup.lua

      - name: Renew OCI public ip
        run: lua oci-renew-ip.lua

      - name: Commit updated ip back to repo
        run: |
          lua oci-publish-ip.lua
      
